//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6MAR_WebApplication {
    
    
  /// <summary>
  /// WebForm114 class.
  /// </summary>
  /// <remarks>
  /// Auto-generated class.
  /// </remarks>
  public partial class WebForm114 {
        
    /// <summary>
    /// Grid1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Grid Grid1;
        
    /// <summary>
    /// TEMPLeditstatusByIcon control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate TEMPLeditstatusByIcon;
        
    /// <summary>
    /// TEMPLcheckboxIsAllocated control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate TEMPLcheckboxIsAllocated;
        
    /// <summary>
    /// EditTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate EditTemplate;
        
    /// <summary>
    /// EditCommandTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate EditCommandTemplate;
        
    /// <summary>
    /// InsertCommandTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate InsertCommandTemplate;
        
    /// <summary>
    /// LoadingFeedbackTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate LoadingFeedbackTemplate;
        
    /// <summary>
    /// ScrollPopupTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate ScrollPopupTemplate;
        
    /// <summary>
    /// SliderTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate SliderTemplate;
        
    /// <summary>
    /// ComboChooseSystem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.GridServerTemplate ComboChooseSystem;
        
    /// <summary>
    /// ComboBoxTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.GridServerTemplate ComboBoxTemplate;
        
    /// <summary>
    /// PickerTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.GridServerTemplate PickerTemplate;
        
    /// <summary>
    /// SQL_applicationList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource SQL_applicationList;
        
    /// <summary>
    /// SQL_entitlementList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource SQL_entitlementList;
        
    /// <summary>
    /// ComboBox1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ComboBox ComboBox1;
    protected global::ComponentArt.Web.UI.ComboBox COMBOXchooseApp;

    protected global::System.Web.UI.WebControls.Panel PANELcond_changesExist;
    protected global::System.Web.UI.WebControls.Panel PANELcond_goback;
    protected global::System.Web.UI.WebControls.Panel PANELcond_readonly;

  }
}
