//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6MAR_WebApplication {
    
    
    /// <summary>
    /// WebForm131 class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class WebForm131 {


        protected global::ComponentArt.Web.UI.Menu GridContextMenu;
        protected global::ComponentArt.Web.UI.Menu GridContextMenuNOEDIT;
		protected global::System.Web.UI.WebControls.Panel PanelEditButtons;
		protected global::System.Web.UI.WebControls.Panel PanelMacroActionsEDIT;
        protected global::ComponentArt.Web.UI.Grid Grid1;
        protected global::ComponentArt.Web.UI.ClientTemplate TEMPLeditstatusByIcon;
        protected global::ComponentArt.Web.UI.ClientTemplate ScrollPopupTemplate;
        protected global::ComponentArt.Web.UI.GridServerTemplate TEMPLATEOrgAxisList;
        protected global::ComponentArt.Web.UI.GridServerTemplate TEMPLATEsaprole;



        protected global::ComponentArt.Web.UI.ComboBox COMBOBOXtype; 
        protected global::ComponentArt.Web.UI.ComboBox COMBOBOXaccesslevel;
        protected global::ComponentArt.Web.UI.GridServerTemplate TEMPLATEOrgValue;
        protected global::System.Web.UI.WebControls.HiddenField HIDDENidWS;
        protected global::System.Web.UI.WebControls.HiddenField HIDDENeditmode;

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected global::System.Web.UI.WebControls.SqlDataSource SQL_WorkspaceDetails;


    }
}
