INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Approva BizRights');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('AS/400');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Audio Conferencing');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Axentis');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('BASIS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Blackberry - Administration');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('BOSS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Business Objects (Cold Drink)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Cincom');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('CMA');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Concur');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('CPACT');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('DB2');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Ebydos Webcycle Application');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('ECAPS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('EPIC');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('eSourcing');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('EtQ');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('EWR');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('FileNET (eRepository)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Financial Image Retrieval System (Graphic Data)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('IGE Application Access');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('inSight');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Intranet Admin');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('iVault');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('IWR');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('KRONOS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Live Meeting');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Lotus Notes');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('MAP');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Margin Minder');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Material Inventory Management (MIM)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Maximo Line 5.2');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('MS SQL Server');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('NA FASETS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('NA LAN Desk');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('NA Windows 2000 File and Print');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('OCS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Open VMS');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Optical BE & NL');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Oracle Transport Manager (OTM)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Outlook');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('PAT Reporting');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Payment Hub');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('PlanView');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('PROD/400');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('ProWatch');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Quest');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('RACF');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Robot Authority (Robot/SAVE)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('SAP');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Sharepoint (Base Access)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('SKEP Purchasing/Planning');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Stock Nucleus');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Streaming Video/Audio Internet Access');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Terprod - Teradata');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Tivoli Workstation Scheduler (TWS)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Tracking and Tracing');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('UFP (Forecasting, KAEP, Monthly Planning)');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Verzuimmanager');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('VPN');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('Windows Servers');
INSERT INTO t_RBSR_AUFW_u_Application (c_u_Name) VALUES ('WMS');
