//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6MAR_WebApplication {
    
    
    /// <summary>
    /// WebForm16 class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class WebForm16 {
        
        /// <summary>
        /// PANELcond_Editable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PANELcond_Editable;
        
        /// <summary>
        /// PANELcond_ViewOtherUserWorkspace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PANELcond_ViewOtherUserWorkspace;
        
        /// <summary>
        /// PANELcond_ViewActiveReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PANELcond_ViewActiveReadOnly;
        
        /// <summary>
        /// PANELcond_ViewHistoricalReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PANELcond_ViewHistoricalReadOnly;
        
        /// <summary>
        /// PANELcond_ReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PANELcond_ReadOnly;
        
        /// <summary>
        /// SqlDataSource1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
      protected global::System.Web.UI.WebControls.SqlDataSource SQL_additionalRoles;



      protected global::System.Web.UI.WebControls.HiddenField HIDDENcurbrole;
      
        
        /// <summary>
        /// Grid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Grid Grid1;
      protected global::ComponentArt.Web.UI.Grid GRIDadditionalRoles;


      protected global::ComponentArt.Web.UI.CallBack CALLBACKadditionalRoles;
      protected global::ComponentArt.Web.UI.CallBack CALLBACKinitChangeMgmt;


      protected global::ComponentArt.Web.UI.ComboBox COMBOXchooseApp;
        
        /// <summary>
        /// TEMPLdesignLinkage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate TEMPLdesignLinkage;
        
        /// <summary>
        /// EditCommandTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate EditCommandTemplate;
        
        /// <summary>
        /// DLGbusroleProperties control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DLGbusroleProperties;
    }
}
